{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fusionauth.fullname" . }}-secret
  labels:
    {{- include "fusionauth.labels" . | nindent 4 }}
type: Opaque
data:
  # For production, create your own secret:
  # kubectl create secret generic fusionauth-secret \
  #   --from-literal=database-password=<password> \
  #   --from-literal=database-root-password=<root-password>
  {{ .Values.database.secretKey }}: {{ randAlphaNum 24 | b64enc | quote }}
  {{- if not .Values.database.root.existingSecret }}
  {{ .Values.database.root.secretKey }}: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
