#!/usr/bin/env python3
import os
import subprocess

feature = os.environ.get('FEATURE', '')
slug = os.environ.get('SLUG', '')
scope = os.environ.get('SCOPE', 'N/A')
branch = os.environ.get('BRANCH', '')

pr_body = f"""## {feature}

Auto-generated implementation scaffold from Ship Pipeline.

**Priority**: P0/P1 competitive gap
**Estimated Scope**: {scope}

### What's Done
- Backend handler/service scaffold created
- Frontend component/store scaffold created
- Ready for implementation

### TODO
- [ ] Implement actual feature logic
- [ ] Add database migrations
- [ ] Write unit tests
- [ ] Run manual code review
- [ ] Test integration end-to-end

---
*Generated by Ship Pipeline*
"""

title = f"feat({slug}): {feature}"

result = subprocess.run(
    ['gh', 'pr', 'create',
     '--title', title,
     '--body', pr_body,
     '--base', 'develop',
     '--head', branch],
    capture_output=True,
    text=True
)

if result.returncode == 0:
    print("PR created")
else:
    print(f"PR creation output: {result.stdout}")
    if result.stderr:
        print(f"PR creation error: {result.stderr}")
