package services

import (
	"context"
	"errors"
	"testing"
	
	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"hearth/internal/models"
)

// MockSvelteRepository is an autogenerated mock type for the SvelteRepository type
type MockSvelteRepository struct {
	mock.Mock
}

func (m *MockSvelteRepository) GetUserSettings(ctx context.Context, userID models.UserID) (*models.SvelteUserSettings, error) {
	args := m.Called(ctx, userID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*models.SvelteUserSettings), args.Error(1)
}

func (m *MockSvelteRepository) UpdateUserSettings(ctx context.Context, settings *models.SvelteUserSettings) error {
	args := m.Called(ctx, settings)
	return args.Error(0)
}

// We add CreateOrUpdateAvatar as it was implied in SetServerAvatar
func (m *MockSvelteRepository) CreateOrUpdateAvatar(ctx context.Context, serverID models.ServerID, imageData []byte) error {
	args := m.Called(ctx, serverID, imageData)
	return args.Error(0)
}

func (m *MockSvelteRepository) GetAvatarData(ctx context.Context, serverID models.ServerID) ([]byte, error) {
	args := m.Called(ctx, serverID)
	return args.Get(0).([]byte), args.Error(1)
}

func TestSvelteService_GetSettings(t *testing.T) {
	// Arrange
	ctx := context.Background()
	userID := models.UserID(uuid.New().String())
	mockRepo := new(MockSvelteRepository)
	
	expectedSettings := &models.SvelteUserSettings{
		UserID: userID,
		Theme:  "dark",
	}
	mockRepo.On("GetUserSettings", ctx, userID).Return(expectedSettings, nil)
	
	service := NewSvelteService(mockRepo)
	
	// Act
	result, err := service.GetSettings(ctx, userID)
	
	// Assert
	assert.NoError(t, err)
	assert.Equal(t, expectedSettings, result)
	mockRepo.AssertExpectations(t)
}

func TestSvelteService_GetSettings_EmptyUser(t *testing.T) {
	ctx := context.Background()
	mockRepo := new(MockSvelteRepository)
	service := NewSvelteService(mockRepo)
	
	_, err := service.GetSettings(ctx, "")
	
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "user id cannot be empty")
}

func TestSvelteService_UpdateSettings_Success(t *testing.T) {
	// Arrange
	ctx := context.Background()
	userID := models.UserID(uuid.New().String())
	settings := &models.SvelteUserSettings{
		UserID: userID,
		AutoSaveMessages: true,
	}
	mockRepo := new(MockSvelteRepository)
	mockRepo.On("UpdateUserSettings", ctx, settings).Return(nil)
	
	service := NewSvelteService(mockRepo)
	
	// Act
	err := service.UpdateSettings(ctx, settings)
	
	// Assert
	assert.NoError(t, err)
	mockRepo.AssertExpectations(t)
}

func TestSvelteService_UpdateSettings_ValidationError(t *testing.T) {
	// Arrange
	ctx := context.Background()
	userID := models.UserID(uuid.New().String())
	settings := &models.SvelteUserSettings{
		UserID: userID,
		AutoSaveMessages: true,
		// Invalid retention
		MessageRetentionDays: 0, 
	}
	mockRepo := new(MockSvelteRepository)
	
	service := NewSvelteService(mockRepo)
	
	// Act
	err := service.UpdateSettings(ctx, settings)
	
	// Assert
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "retention period")
	mockRepo.AssertNotCalled(t, "UpdateUserSettings")
}

func TestSvelteService_SetServerAvatar(t *testing.T) {
	// Arrange
	ctx := context.Background()
	serverID := models.ServerID(uuid.New().String())
	imageData := []byte{255, 0, 255} // Purple pixel
	mockRepo := new(MockSvelteRepository)
	
	// Mock GetAvatarData to simulate a successful read before update
	mockRepo.On("GetAvatarData", ctx, serverID).Return(imageData, nil)
	mockRepo.On("CreateOrUpdateAvatar", ctx, serverID, imageData).Return(nil)
	
	service := NewSvelteService(mockRepo)
	
	// Act
	err := service.SetServerAvatar(ctx, serverID, imageData)
	
	// Assert
	assert.NoError(t, err)
	mockRepo.AssertExpectations(t)
}

func TestSvelteService_SetServerAvatar_EmptyServerID(t *testing.T) {
	ctx := context.Background()
	imageData := []byte{255, 0, 255}
	service := NewSvelteService(new(MockSvelteRepository))
	
	err := service.SetServerAvatar(ctx, "", imageData)
	
	assert.Error(t, err)
}

func TestSvelteService_SetServerAvatar_RepoError(t *testing.T) {
	ctx := context.Background()
	serverID := models.ServerID(uuid.New().String())
	imageData := []byte{255, 0, 255}
	mockRepo := new(MockSvelteRepository)
	
	repoErr := errors.New("database failed")
	mockRepo.On("GetAvatarData", ctx, serverID).Return([]byte{}, repoErr)
	
	service := NewSvelteService(mockRepo)
	err := service.SetServerAvatar(ctx, serverID, imageData)
	
	assert.Error(t, err)
	assert.Equal(t, repoErr, err)
}